name: Build and deploy
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
      env:
         CI: ""
         
    - name: Stop server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO1_SSH_HOST }}
        username: ${{ secrets.DO1_SSH_USER }}
        key: ${{ secrets.DO1_SSH_PRIVATE_KEY }}
        port: ${{ secrets.DO1_SSH_PORT }}
        script: |
          pm2 del server
          
    - name: Copy build assets to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          username: '${{ secrets.DO1_SSH_USER }}'
          server: '${{ secrets.DO1_SSH_HOST }}'
          ssh_private_key: ${{ secrets.DO1_SSH_PRIVATE_KEY_PEM }}
          local_path: './build/*'
          remote_path: ' ${{ secrets.DO1_REMOTE_BUILD_PATH }}/build'
          sftpArgs: '-o ConnectTimeout=10'

    - name: Start server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO1_SSH_HOST }}
        username: ${{ secrets.DO1_SSH_USER }}
        key: ${{ secrets.DO1_SSH_PRIVATE_KEY }}
        port: ${{ secrets.DO1_SSH_PORT }}
        script: |
          cd chat
          git reset --hard
          git pull
          npm i
          pm2 start src/server.js
          sleep 5
          pm2 l
         
