name: Build and deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
      env:
         CI: ""
    - name: deploy build folder to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          username: '${{ secrets.DO1_SSH_USER }}'
          server: '${{ secrets.DO1_SSH_HOST }}'
          ssh_private_key: ${{ secrets.DO1_SSH_PRIVATE_KEY }}
          local_path: './build/*'
          remote_path: ' ${{ secrets.DO1_REMOTE_BUILD_PATH }}/build'
          sftpArgs: '-o ConnectTimeout=5'

    - name: Test SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO1_SSH_HOST }}
        username: ${{ secrets.DO1_SSH_USER }}
        key: ${{ secrets.DO1_SSH_PRIVATE_KEY }}
        port: ${{ secrets.DO1_SSH_PORT }}
        script:  |
          cd repos/Chat
          git pull
          pm2 l
          pm2 del 0
          pm2 start src/server.js
          pm2 l
         
